### ISSUE TITLE
Config YAML

### ISSUE THREAD

**Issue by mathhyyn** [OnionGrief/Automatic-Chipollino-Update#1]
структура:

```yaml
chipollino_path: ./Chipollino # путь до конвертера

# типы интерпретатора
types:
  NFA: # имя
    class: FiniteAutomaton # реализуемый класс
    children: [DFA] # вложенные типы
    ru_str: автомат # обозначение для шаблонов
 ...

# классы в бэке
classes:
  FiniteAutomaton: # имя
    file: FiniteAutomaton # имя файла
    extends: AbstractMachine # наследуемый класс
...

 # функции интерпретатора
functions:
 - name: Thompson # имя в интерпретаторе
   prog_name: to_thompson # имя в коде бэка
   return_type: NFA # возвращаемый тип
   arguments: [Regex] # типы принимаемых аргументов
   need_template: true # флаг генерации шаблонов
 ...
```
